name: eecs6322-a3
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.23.5
  - pillow=9.3.0
  - pip=22.3.1
  - python=3.10.9
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pip:
      - timm==0.6.12
      - torchtext==0.14.1